name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]*\.[0-9]*\.[0-9]*'

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/heygen-test-python

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Unnamed as prep not assumed to fail
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
